[build]
  # If you’re not running any build command and serving straight
  # from the project root, you can leave `publish = "."`
  publish = "."

[[redirects]]
  from = "/contact"
  to   = "/contact.html"
  status = 200
  force = true
